services:
  - type: worker
    name: telegram-link-manager-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        value: ""   # isi token BotFather di Render dashboard
